"use client";
import { useState } from "react";

export default function Accordion() {
  const [expandedIndex, setExpandedIndex] = useState<number | null>(null);

  const accordionData = [
  {
    title: "What is this platform used for?",
    content: "This dashboard helps financial analysts track, investigate, and resolve high-risk or suspicious transactions using AI-powered alerts and audit trails.",
  },
  {
    title: "How are alerts generated?",
    content: "Alerts are generated by our AI models based on transaction patterns, anomaly detection, fraud likelihood, and predefined financial rules.",
  },
  {
    title: "Who can resolve an alert?",
    content: "Only authenticated analysts or admins with access privileges can resolve, investigate, or update an alert status.",
  },
  {
    title: "What does each alert status mean?",
    content: `"UNRESOLVED" indicates a fresh alert, "INVESTIGATING" means an analyst is reviewing it, and "RESOLVED" means the issue has been verified and closed.`,
  },
  {
    title: "What happens when an alert is resolved?",
    content: "Once resolved, the associated transaction is marked safe. If it was previously flagged as fraud, it will be unmarked and the account's fraud count updated.",
  },
  {
    title: "Is my data secure?",
    content: "Yes. We use HTTPS for all communications, and sensitive information is encrypted at rest and in transit.",
  },
  {
    title: "Who do I contact for support?",
    content: "Reach out to your internal FinOps admin or support@yourdomain.com for technical help or access issues.",
  },
  {
    title:"Why can I not create new account?",
    content:"This project is only a prototype and the ML model requires at least 100+ transactions for a new account as it is user behaviour based. Hence we use pre-defined accounts where it stimulats real life ML powered fraud detection system."
  },
  {
    title:"How precise is the ML model?",
    content:"The statistics of the model are Precision score of about 81.32%, Recall score(default threshold) of about 88.1%, F1-score of about 84.57% and ROC AUC score of about 99.09%."
  }
  ];


  const toggleAccordion = (index: number) => {
    setExpandedIndex(prev => (prev === index ? null : index));
  };

  return (
    <div className="space-y-4">
      {accordionData.map((item, index) => {
        const isExpanded = expandedIndex === index;

        return (
          <div
            key={index}
            className={`bg-gradient-to-br from-black via-black to-white border-white border rounded-xl overflow-hidden transition-all duration-300 ${
              isExpanded ? "max-h-96 bg-black" : "max-h-20"
            }`}
          >
            <div
              className="flex justify-between p-6 items-start cursor-pointer"
              onClick={() => toggleAccordion(index)}
            >
              <div className="text-2xl font-bold text-white/80">{item.title}</div>
              <span className="text-xl">{isExpanded ? "▲" : "▼"}</span>
            </div>
            <div
              className={`px-5 pb-5 overflow-hidden text-white font-mono transition-all duration-300 ${
                isExpanded ? "opacity-100 bg-black" : "opacity-0"
              }`}
            >
              {item.content}
            </div>
          </div>
        );
      })}
    </div>
  );
}
